apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: twlagmnow-python 
  janus-idp.io/tekton: twlagmnow-python
  backstage.io/kubernetes-id: twlagmnow-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: twlagmnow-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml