apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: twlagmnow-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:34cbb945b5182bdd0f96ed2fb3b97250a48bcc5a@sha256:766aed54f4ac4230d407d465b4b4de0e928b9e78ed72e187859afebeed7598ee
          name: container-image
